
# https://setuptools.readthedocs.io/en/latest/userguide/quickstart.html
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

# To Build, use https://pypa-build.readthedocs.io/en/latest/index.html
# $ python -m build